runtime: nodejs18
service: backend-service
env: standard

instance_class: F2

env_variables:
  NODE_ENV: production
  MONGO_URI: "mongodb+srv://pranavko12:9004270429pk1211@fav.cvg6p.mongodb.net/?retryWrites=true&w=majority&appName=Fav"
  TOMORROW_API_KEY: "i6t0LkaUvOG0zoHXaPSBJd0Scev0fDxH"


handlers:
  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 10